server {
    listen 80;
    server_name agkb360.app www.agkb360.app;
    
    # Redirect HTTP ke HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name agkb360.app www.agkb360.app;
    root /var/www/html;
    index index.php index.html;

    ssl_certificate /etc/letsencrypt/live/agkb360.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/agkb360.app/privkey.pem;

    # Allow Certbot challenge
    location ~ /.well-known/acme-challenge {
        allow all;
        root /var/www/html;
    }

    # Route /ktb360
    location /ktb360 {
        try_files $uri $uri/ /ktb360/index.php?$query_string;
    }

    # Routing semua request ke index.php
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP processing
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Block akses ke file sensitif
    location ~ /\. {
        deny all;
    }
}