server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php index.html;

    # Route /demo
    location /demo {
        try_files $uri $uri/ /demo/index.php?$query_string;
    }

    # Route /app
    location /app {
        try_files $uri $uri/ /app/index.php?$query_string;
    }

    # Root
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP processing
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Block akses ke file sensitif
    location ~ /\. {
        deny all;
    }
}